# Connect to the MySQL.
connection:
  host: "jdbc:mysql://localhost:3306/test"
  username: "root"
  password: ""

# The message send to the player who need to complete survey.
button_message: "&6Click here to do survey!"

# If player exit the game while doing survey, send this message when they join the game again.
restart_message: "&6You still have survey to complete, click me to continue!"

# The questions that player need to answer.
questions:
  - "How..."
  - "What..."
  - "Why..."

# Minimum number of characters to answer
min: 20

# The message send to the player if their answer is not valid
invalid_message: "&cPlease enter a full sentence as an answer."

# The message send to the player when they complete one question
complete_one_message: "&3Got it!"

# The message send to the player when they complete all questions
complete_all_message: "&6&lThank you!"

# Survey interval (hours)
interval: 12